services:
  db:
    image: postgres:15
    container_name: eco_monitoring_db
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./eco_monitoring_db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10
  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: eco_monitoring_api
    restart: always
    ports:
      - "${API_PORT}:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
